### ISSUE TITLE
使用taiyi_xl_minimal_inference.py推理huggingface上的模型报错

### ISSUE THREAD

**Issue by shyshuai90** [IDEA-CCNL/Taiyi-Diffusion-XL#7]
您好，如题，原始模型是从huggingface上直接下载的，我在taiyi_xl_minimal_inference.py中修改了加载的位置

`  
  
    # todo
    args.ckpt_path = "/Volumes/Taiyi-Stable-Diffusion-XL-3.5B/taiyi_diffusion_xl.safetensors"

    # todo
    # HuggingFaceのmodel id
    PRETRAINED_MODEL_DIR = "/Volumes/Taiyi-Stable-Diffusion-XL-3.5B"
    text_encoder_1_name = f"{PRETRAINED_MODEL_DIR}/tokenizer"
    text_encoder_2_name = f"{PRETRAINED_MODEL_DIR}/tokenizer_2"
`

推理的log如下

`
(sd) ➜  Taiyi-Diffusion-XL git:(debug) ✗ python taiyi_xl_minimal_inference.py
building U-Net
loading U-Net from checkpoint
U-Net:  <All keys matched successfully>
building text encoders
使用taiyi模型微调！
loading text encoders from checkpoint
Traceback (most recent call last):
  File "/Users/codes/Taiyi-Diffusion-XL/taiyi_xl_minimal_inference.py", line 267, in <module>
    text_model1, text_model2, vae, unet, _, _ = sdxl_model_util.load_models_from_sdxl_checkpoint(
  File "/Users/codes/Taiyi-Diffusion-XL/library/sdxl_model_util.py", line 275, in load_models_from_sdxl_checkpoint
    info1 = _load_state_dict_on_device(text_model1, te1_sd, device=map_location)  # remain fp32
  File "/Users/codes/Taiyi-Diffusion-XL/library/sdxl_model_util.py", line 158, in _load_state_dict_on_device
    raise RuntimeError("Error(s) in loading state_dict for {}:\n\t{}".format(model.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for CLIPTextModel:
        Unexpected key(s) in state_dict: "text_model.embeddings.position_ids". 

`

**Comment by wxj630** [comment]
你的transformers版本是多少？

**Comment by shyshuai90** [comment]
> 你的transformers版本是多少？

好的，transformers改成 requirements.txt中的版本就可以了！ 感谢回复！

**Comment by wxj630** [comment]
不客气～

**Comment by yangy996** [comment]
> 不客气～

大佬，如果我想升级transformers版本，这个应该怎么办呢？由于别的几个模型用的版本比较高，导致也会出现这个错误

**Comment by wxj630** [comment]
> > 不客气～
> 
> 大佬，如果我想升级transformers版本，这个应该怎么办呢？由于别的几个模型用的版本比较高，导致也会出现这个错误

找到text_model.load_state_dict(converted_text_encoder_checkpoint)，改成text_model.load_state_dict(converted_text_encoder_checkpoint, strict = False)

**Comment by yangy996** [comment]
> > > 不客气～
> > 
> > 
> > 大佬，如果我想升级transformers版本，这个应该怎么办呢？由于别的几个模型用的版本比较高，导致也会出现这个错误
> 
> 找到text_model.load_state_dict(converted_text_encoder_checkpoint)，改成text_model.load_state_dict(converted_text_encoder_checkpoint, strict = False)

大佬，不好使呀，还是会报这个错误
![image](https://github.com/IDEA-CCNL/Taiyi-Diffusion-XL/assets/15188456/e45c6e53-1765-497d-b935-700da66fc8e4)
![8f49173391c1492d1f16b49268bbb574](https://github.com/IDEA-CCNL/Taiyi-Diffusion-XL/assets/15188456/66474d67-f609-4cd9-9e3b-acda1395002d)

**Comment by wxj630** [comment]
https://github.com/IDEA-CCNL/Taiyi-Diffusion-XL/blob/main/library/sdxl_model_util.py 
第158行的raise RuntimeError注释掉应该就可以了

**Comment by yangy996** [comment]
> https://github.com/IDEA-CCNL/Taiyi-Diffusion-XL/blob/main/library/sdxl_model_util.py 第158行的raise RuntimeError注释掉应该就可以了

大佬，实在不好意思，再打扰下，还是有点问题，transformers==4.33.2后，又出现新的问题
![image](https://github.com/IDEA-CCNL/Taiyi-Diffusion-XL/assets/15188456/b31bf74b-7f14-46c4-bc4a-6ee14f1503a0)

![image](https://github.com/IDEA-CCNL/Taiyi-Diffusion-XL/assets/15188456/9888bb3f-77fe-4173-9a2d-f74f3b545170)

**Comment by wxj630** [comment]
先删除position_ids试下：
del text_model1["embeddings.position_ids"]
del text_model2["embeddings.position_ids"]

再去正常to(self.device)

**Comment by yangy996** [comment]
> 先删除position_ids试下： del text_model1["embeddings.position_ids"] del text_model2["embeddings.position_ids"]
> 
> 再去正常to(self.device)

不行，没有这个
![image](https://github.com/IDEA-CCNL/Taiyi-Diffusion-XL/assets/15188456/14f78405-1431-4c07-bac6-59230a14ca7c)

**Comment by yangy996** [comment]
> text_model1

text_model1打印数据如下：
![image](https://github.com/IDEA-CCNL/Taiyi-Diffusion-XL/assets/15188456/6f556e64-2d62-43e5-9318-eecc8d0fe65d)

**Comment by wxj630** [comment]
> https://github.com/IDEA-CCNL/Taiyi-Diffusion-XL/blob/main/library/sdxl_model_util.py 第158行的raise RuntimeError注释掉应该就可以了

那在这里同样的函数，在函数最开始，删掉state_dict里的embeddings.position_ids，就不会有unexcepted key(s)了

查看huggingface的源码https://github.com/huggingface/transformers/blob/main/src/transformers/models/clip/modeling_clip.py第202行，position_ids会在缓存里自己生成，所以我们在删掉是没事的

**Comment by yangy996** [comment]
> embeddings.position_ids

不行，预测的时候，还是报错

**Comment by wxj630** [comment]
报啥错

**Comment by yangy996** [comment]
> 报啥错

https://github.com/IDEA-CCNL/Taiyi-Diffusion-XL/issues/7#issuecomment-2148882903

**Comment by wxj630** [comment]
<img width="1374" alt="image" src="https://github.com/IDEA-CCNL/Taiyi-Diffusion-XL/assets/19636285/a4b24576-ba61-4f0d-98ec-a51bc2648102">
你好，我测试这样改是可以的，transformers==4.33.2

**Comment by yangy996** [comment]
> <img alt="image" width="1374" src="https://private-user-images.githubusercontent.com/19636285/336730313-a4b24576-ba61-4f0d-98ec-a51bc2648102.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NzI2OTAsIm5iZiI6MTcxNzU3MjM5MCwicGF0aCI6Ii8xOTYzNjI4NS8zMzY3MzAzMTMtYTRiMjQ1NzYtYmE2MS00ZjBkLTk4ZWMtYTUxYmMyNjQ4MTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA3MjYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2ODliOWZmMTYzY2EwMTZkMTU5YzM4NGJjYTVkMjgyNDU1ODY0YWZiNjYyZjcwYWI3NTdmYTMzMDJjNDA5Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m2O7-2Ps0gPHkX8ey6VOdTgNvQvRvpqd-qC6dgiqYpI"> 你好，我测试这样改是可以的，transformers==4.33.2

🐮，可以了，按大佬这个方式改正常了
